/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import entity.ChiTietHoaDon;
import entity.HoaDon;
import entity.SanPham;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class DiaLog_DSSP_HD extends javax.swing.JFrame {
    private static HoaDon hd;
    private static ArrayList<ChiTietHoaDon> dsSP;
    /**
     * Creates new form DiaLog_DSSP_HD
     */
    public DiaLog_DSSP_HD(HoaDon hd, ArrayList<ChiTietHoaDon> dsSP) {
        initComponents();
        this.hd = hd;
        this.dsSP = dsSP;
        setDefaultCloseOperation(1);
        setLocationRelativeTo(null);
        setSize(1200, 600);
   
        DocDSSPLenTable();
    }
    
    public void DocDSSPLenTable() {
        DefaultTableModel temp = (DefaultTableModel) tbl_DSSP.getModel();
        
        for(ChiTietHoaDon cthd : dsSP) {
            SanPham sp = cthd.getSanPham();
            Object[] obj = {sp.getMaSP(), sp.getTenSP(), cthd.getSoLuong(), sp.getThue(), 
                sp.getkM(), sp.getGiaBan() * cthd.getSoLuong() * (1 - sp.getThue() / 100)};
            
           temp.addRow(obj);
        }
    }
    
    public void DocDuLieuHoaDon() {
        txt_MaHD.setText(hd.getMaHD());
        txt_SDTD.setText(hd.getSuDungTichDiem() + "");
        txt_TienNhan.setText(hd.getTienKhachDua() + "");
        txt_TongThue.setText(hd.getTongThue() + "");
        txt_TongKM.setText(hd.getTongKM() + "");
        txt_ThanhTien.setText(hd.getTongTien() + "");
        txt_TienThoi.setText(hd.getTongTien() - hd.getTienKhachDua() - hd.getSuDungTichDiem() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_MaHD = new javax.swing.JTextField();
        pnl_Center = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DSSP = new javax.swing.JTable();
        pnl_Bot = new javax.swing.JPanel();
        pnl_TSDichDiem = new javax.swing.JPanel();
        lbl_SDTD = new javax.swing.JLabel();
        txt_SDTD = new javax.swing.JTextField();
        pnl_TienNhan = new javax.swing.JPanel();
        lbl_TienNhan = new javax.swing.JLabel();
        txt_TienNhan = new javax.swing.JTextField();
        pnl_TienThoi = new javax.swing.JPanel();
        lbl_TienThoi = new javax.swing.JLabel();
        txt_TienThoi = new javax.swing.JTextField();
        pnl_TongThue = new javax.swing.JPanel();
        lbl_TongThue = new javax.swing.JLabel();
        txt_TongThue = new javax.swing.JTextField();
        pnl_TongKM = new javax.swing.JPanel();
        lbl_TongKM = new javax.swing.JLabel();
        txt_TongKM = new javax.swing.JTextField();
        pnl_ThanhTien = new javax.swing.JPanel();
        lbl_ThanhTien = new javax.swing.JLabel();
        txt_ThanhTien = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Mã Hóa Đơn:");
        pnl_Top.add(jLabel1);

        txt_MaHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_MaHD.setPreferredSize(new java.awt.Dimension(500, 40));
        pnl_Top.add(txt_MaHD);

        getContentPane().add(pnl_Top, java.awt.BorderLayout.PAGE_START);

        pnl_Center.setLayout(new java.awt.BorderLayout());

        tbl_DSSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên", "Số lượng", "Thuế", "Khuyến Mãi", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(tbl_DSSP);

        pnl_Center.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnl_Center, java.awt.BorderLayout.CENTER);

        pnl_Bot.setPreferredSize(new java.awt.Dimension(927, 150));
        pnl_Bot.setLayout(new java.awt.GridLayout(2, 3));

        lbl_SDTD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_SDTD.setText("Sử dụng điểm: ");
        pnl_TSDichDiem.add(lbl_SDTD);

        txt_SDTD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_SDTD.setPreferredSize(new java.awt.Dimension(200, 35));
        pnl_TSDichDiem.add(txt_SDTD);

        pnl_Bot.add(pnl_TSDichDiem);

        lbl_TienNhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_TienNhan.setText("Tiền Nhận:");
        pnl_TienNhan.add(lbl_TienNhan);

        txt_TienNhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_TienNhan.setPreferredSize(new java.awt.Dimension(200, 35));
        pnl_TienNhan.add(txt_TienNhan);

        pnl_Bot.add(pnl_TienNhan);

        lbl_TienThoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_TienThoi.setText("Tiền thối: ");
        lbl_TienThoi.setPreferredSize(new java.awt.Dimension(100, 25));
        pnl_TienThoi.add(lbl_TienThoi);

        txt_TienThoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_TienThoi.setPreferredSize(new java.awt.Dimension(200, 35));
        pnl_TienThoi.add(txt_TienThoi);

        pnl_Bot.add(pnl_TienThoi);

        lbl_TongThue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_TongThue.setText("Tổng thuế:");
        lbl_TongThue.setPreferredSize(new java.awt.Dimension(130, 25));
        pnl_TongThue.add(lbl_TongThue);

        txt_TongThue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_TongThue.setPreferredSize(new java.awt.Dimension(200, 35));
        pnl_TongThue.add(txt_TongThue);

        pnl_Bot.add(pnl_TongThue);

        lbl_TongKM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_TongKM.setText("Tổng KM:");
        lbl_TongKM.setPreferredSize(new java.awt.Dimension(93, 25));
        pnl_TongKM.add(lbl_TongKM);

        txt_TongKM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_TongKM.setPreferredSize(new java.awt.Dimension(200, 35));
        pnl_TongKM.add(txt_TongKM);

        pnl_Bot.add(pnl_TongKM);

        lbl_ThanhTien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_ThanhTien.setText("Thành Tiền:");
        pnl_ThanhTien.add(lbl_ThanhTien);

        txt_ThanhTien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_ThanhTien.setPreferredSize(new java.awt.Dimension(200, 35));
        pnl_ThanhTien.add(txt_ThanhTien);

        pnl_Bot.add(pnl_ThanhTien);

        getContentPane().add(pnl_Bot, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiaLog_DSSP_HD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiaLog_DSSP_HD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiaLog_DSSP_HD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiaLog_DSSP_HD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiaLog_DSSP_HD(hd, dsSP).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_SDTD;
    private javax.swing.JLabel lbl_ThanhTien;
    private javax.swing.JLabel lbl_TienNhan;
    private javax.swing.JLabel lbl_TienThoi;
    private javax.swing.JLabel lbl_TongKM;
    private javax.swing.JLabel lbl_TongThue;
    private javax.swing.JPanel pnl_Bot;
    private javax.swing.JPanel pnl_Center;
    private javax.swing.JPanel pnl_TSDichDiem;
    private javax.swing.JPanel pnl_ThanhTien;
    private javax.swing.JPanel pnl_TienNhan;
    private javax.swing.JPanel pnl_TienThoi;
    private javax.swing.JPanel pnl_TongKM;
    private javax.swing.JPanel pnl_TongThue;
    private javax.swing.JPanel pnl_Top;
    private javax.swing.JTable tbl_DSSP;
    private javax.swing.JTextField txt_MaHD;
    private javax.swing.JTextField txt_SDTD;
    private javax.swing.JTextField txt_ThanhTien;
    private javax.swing.JTextField txt_TienNhan;
    private javax.swing.JTextField txt_TienThoi;
    private javax.swing.JTextField txt_TongKM;
    private javax.swing.JTextField txt_TongThue;
    // End of variables declaration//GEN-END:variables
}
