/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Asus
 */
public class DiaLog_HoaDon extends javax.swing.JPanel {

    /**
     * Creates new form DiaLog_HoaDon
     */
    public DiaLog_HoaDon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_top = new javax.swing.JPanel();
        lbl_ThanhToan = new javax.swing.JLabel();
        pnl_center = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnl_top.setBackground(new java.awt.Color(255, 0, 0));
        pnl_top.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 15, 1));
        pnl_top.setLayout(new java.awt.BorderLayout());

        lbl_ThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_ThanhToan.setForeground(new java.awt.Color(0, 0, 0));
        lbl_ThanhToan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ThanhToan.setText("Hóa Đơn");
        pnl_top.add(lbl_ThanhToan, java.awt.BorderLayout.CENTER);

        add(pnl_top, java.awt.BorderLayout.PAGE_START);

        pnl_center.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        pnl_center.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(pnl_center, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_ThanhToan;
    private javax.swing.JPanel pnl_center;
    private javax.swing.JPanel pnl_top;
    // End of variables declaration//GEN-END:variables
}
