/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;


import dao.SanPham_DAO;
import entity.KhuyenMai;
import entity.NhaCungCap;
import entity.SanPham;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class Panel_Product extends javax.swing.JPanel {
    private SanPham_DAO sp_dao = new SanPham_DAO();
    /**
     * Creates new form Panel_Product
     */
    public Panel_Product() {
        initComponents();
        DocLieuLenTableSanPham();
    }
    
    public boolean validData_SanPham(){
        String maSP = maSP_field.getText().toString().trim();
        String tenSP = tenSP_field.getText().toString().trim();
        String giaNhap = giaNhap_field.getText().toString().trim();
        String giaBan = giaBan_field.getText().toString().trim();
        String tonKho = tonKho_field.getText().toString().trim();
        String khuyenMai = khuyenMai_field.getText().toString().trim();
        String bayBan = bayban_field.getText().toString().trim();
        
        if(maSP.isEmpty() || (!maSP.matches("^SP\\d{3}$"))){
            JOptionPane.showMessageDialog(this, "Mã sản phẩm phải theo mẫu SP001");
            return false;
        }
        if(tenSP.isEmpty()){
            JOptionPane.showMessageDialog(this, "Tên sản phẩm không được rỗng!");
            return false;
        }
        double giaNhapHang = Double.parseDouble(giaNhap);
        if(giaNhapHang <= 0 || giaNhap.isEmpty()){
            JOptionPane.showMessageDialog(this, "Gía nhập hàng phải lớn hơn 0");
        }
        double giaBanHang = Double.parseDouble(giaBan);
        if(giaBanHang <= 0  || giaBan.isEmpty()){
            JOptionPane.showMessageDialog(this, "Gía bán hàng phải lớn hơn 0");
        }
        int slBayBan = Integer.parseInt(bayBan);
        if(slBayBan <= 0){
            JOptionPane.showMessageDialog(this, "Số lượng bày bán phải lớn hơn 0");
            return false;
        }
        int slTonKho = Integer.parseInt(tonKho);
        if(slTonKho <= 0){
            JOptionPane.showMessageDialog(this, "Số lượng tồn kho phải lớn hơn 0");
            return false;
        }
        return true;
    }
    public void DocLieuLenTableSanPham(){
        ArrayList<SanPham> dsSP = sp_dao.getDSSP();
        DefaultTableModel temp = (DefaultTableModel) tbl_sanPham.getModel();
        
        for(SanPham sp : dsSP){
            Object[] obj = {sp.getMaSP(), sp.getTenSP(), sp.getLoaiSP(), sp.getGiaNhapHang(), sp.getGiaBan(), sp.getSoLuongTonKho(), sp.getnCC().getMaNCC(), sp.getkM().getMaKM(), sp.getSoLuongBayBan()};
            temp.addRow(obj);
        }         
    }
    
    public void XoaDuLieuTableSP(){
        DefaultTableModel temp = (DefaultTableModel) tbl_sanPham.getModel();
        temp.getDataVector().removeAllElements();
    }
    
    public SanPham createSP(){
        String maSP = maSP_field.getText();
        String tenSP = tenSP_field.getText();
        String cbo_loaiSP = String.valueOf(cbo_loaiSP_field.getSelectedItem());
        double giaNhap = Double.parseDouble(giaNhap_field.getText());
        double giaBan = Double.parseDouble(giaBan_field.getText());
        int tonKho = Integer.parseInt(tonKho_field.getText());
        String cbo_NCC = String.valueOf(cbo_NCC_field.getSelectedItem());
        String khuyenMai = khuyenMai_field.getText();
        int bayBan = Integer.parseInt(bayban_field.getText());
        
        SanPham sp = new SanPham(maSP, new KhuyenMai(khuyenMai), new NhaCungCap(cbo_NCC), tenSP, cbo_loaiSP,giaNhap, giaBan, bayBan, tonKho, 0);
        return sp;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnl_sanPham = new javax.swing.JPanel();
        pnl_Top = new javax.swing.JPanel();
        pnl_info = new javax.swing.JPanel();
        pnl_info1 = new javax.swing.JPanel();
        pnl_maSP = new javax.swing.JPanel();
        lbl_masp = new javax.swing.JLabel();
        maSP_field = new javax.swing.JTextField();
        pnl_NCC = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_NCC = new javax.swing.JLabel();
        cbo_NCC_field = new javax.swing.JComboBox<>();
        pnl_TonKho = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tonKho_field = new javax.swing.JTextField();
        pnl_info2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tenSP_field = new javax.swing.JTextField();
        giaNhap_field = new javax.swing.JTextField();
        khuyenMai_field = new javax.swing.JTextField();
        pnl_info3 = new javax.swing.JPanel();
        lbl_loai = new javax.swing.JLabel();
        lbl_giaBan = new javax.swing.JLabel();
        cbo_loaiSP_field = new javax.swing.JComboBox<>();
        giaBan_field = new javax.swing.JTextField();
        lbl_Bayban = new javax.swing.JLabel();
        bayban_field = new javax.swing.JTextField();
        pnl_btn = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_themMoi = new javax.swing.JButton();
        btn_xoaTrang = new javax.swing.JButton();
        btn_capNhat = new javax.swing.JButton();
        pnl_TimKiem = new javax.swing.JPanel();
        maSP_txt = new javax.swing.JTextField();
        btn_timKiem = new javax.swing.JButton();
        pnl_Center = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        lbl_locTheoGia = new javax.swing.JLabel();
        lbl_locTheoSP = new javax.swing.JLabel();
        lbl_locTheoNCC = new javax.swing.JLabel();
        cbo_locTheoGia = new javax.swing.JComboBox<>();
        cbo_loc_theoSP = new javax.swing.JComboBox<>();
        cbo_locTheoNCC = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sanPham = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnl_sanPham.setLayout(new java.awt.BorderLayout());

        pnl_Top.setPreferredSize(new java.awt.Dimension(0, 320));
        pnl_Top.setLayout(new java.awt.BorderLayout());

        pnl_info.setBackground(new java.awt.Color(255, 255, 255));
        pnl_info.setPreferredSize(new java.awt.Dimension(0, 150));
        pnl_info.setLayout(new java.awt.GridLayout(1, 1));

        pnl_info1.setLayout(new java.awt.GridLayout(3, 1));

        pnl_maSP.setPreferredSize(new java.awt.Dimension(370, 45));
        pnl_maSP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_masp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_masp.setText("Mã SP: ");
        pnl_maSP.add(lbl_masp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        maSP_field.setEnabled(false);
        maSP_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maSP_fieldActionPerformed(evt);
            }
        });
        pnl_maSP.add(maSP_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 200, 40));

        pnl_info1.add(pnl_maSP);

        pnl_NCC.setPreferredSize(new java.awt.Dimension(370, 45));
        pnl_NCC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnl_NCC.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lbl_NCC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_NCC.setText("Nhà cung cấp: ");
        pnl_NCC.add(lbl_NCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        cbo_NCC_field.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbo_NCC_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NCC Gò Vấp", "NCC Tân Bình", "NCC Thủ Đức", "NCC Bình Thạnh" }));
        cbo_NCC_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_NCC_fieldActionPerformed(evt);
            }
        });
        pnl_NCC.add(cbo_NCC_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 200, 40));

        pnl_info1.add(pnl_NCC);

        pnl_TonKho.setPreferredSize(new java.awt.Dimension(370, 45));
        pnl_TonKho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tồn kho:");
        pnl_TonKho.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        tonKho_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tonKho_fieldActionPerformed(evt);
            }
        });
        pnl_TonKho.add(tonKho_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 200, 40));

        pnl_info1.add(pnl_TonKho);

        pnl_info.add(pnl_info1);

        pnl_info2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Tên SP:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Giá nhập:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Khuyến mãi:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, 20));

        tenSP_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenSP_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(tenSP_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 220, 40));

        giaNhap_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giaNhap_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(giaNhap_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 220, 40));
        jPanel1.add(khuyenMai_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 220, 40));

        pnl_info2.add(jPanel1);

        pnl_info.add(pnl_info2);

        pnl_info3.setPreferredSize(new java.awt.Dimension(350, 150));
        pnl_info3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_loai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_loai.setText("Loại:");
        pnl_info3.add(lbl_loai, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        lbl_giaBan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_giaBan.setText("Giá bán:");
        pnl_info3.add(lbl_giaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        cbo_loaiSP_field.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbo_loaiSP_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SGK", "Truyện", "Tiểu thuyết", "Văn phòng phẩm", "Dụng cụ học tập" }));
        pnl_info3.add(cbo_loaiSP_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 230, 40));

        giaBan_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giaBan_fieldActionPerformed(evt);
            }
        });
        pnl_info3.add(giaBan_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 230, 40));

        lbl_Bayban.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Bayban.setText("Bày bán:");
        pnl_info3.add(lbl_Bayban, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        bayban_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayban_fieldActionPerformed(evt);
            }
        });
        pnl_info3.add(bayban_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 230, 40));

        pnl_info.add(pnl_info3);

        pnl_Top.add(pnl_info, java.awt.BorderLayout.NORTH);

        pnl_btn.setPreferredSize(new java.awt.Dimension(1112, 50));
        pnl_btn.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setPreferredSize(new java.awt.Dimension(1020, 50));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_themMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_themMoi.setText("Thêm mới");
        btn_themMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themMoiMouseClicked(evt);
            }
        });
        btn_themMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themMoiActionPerformed(evt);
            }
        });
        jPanel2.add(btn_themMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 130, 60));

        btn_xoaTrang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_xoaTrang.setText("Xóa trắng");
        btn_xoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaTrangActionPerformed(evt);
            }
        });
        jPanel2.add(btn_xoaTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 130, 60));

        btn_capNhat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_capNhat.setText("Cập nhật");
        btn_capNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_capNhatMouseClicked(evt);
            }
        });
        btn_capNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capNhatActionPerformed(evt);
            }
        });
        jPanel2.add(btn_capNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 120, 60));

        pnl_TimKiem.setPreferredSize(new java.awt.Dimension(1112, 60));
        pnl_TimKiem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maSP_txt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        maSP_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maSP_txtActionPerformed(evt);
            }
        });
        pnl_TimKiem.add(maSP_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 980, 60));

        btn_timKiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_timKiem.setText("Tìm kiếm");
        btn_timKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_timKiemMouseClicked(evt);
            }
        });
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });
        pnl_TimKiem.add(btn_timKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, -1, 50));

        jPanel2.add(pnl_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 60));

        pnl_btn.add(jPanel2);

        pnl_Top.add(pnl_btn, java.awt.BorderLayout.CENTER);

        pnl_sanPham.add(pnl_Top, java.awt.BorderLayout.NORTH);

        pnl_Center.setLayout(new java.awt.BorderLayout());
        pnl_sanPham.add(pnl_Center, java.awt.BorderLayout.CENTER);

        add(pnl_sanPham, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel10.setPreferredSize(new java.awt.Dimension(940, 100));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel9.setPreferredSize(new java.awt.Dimension(940, 300));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel11.setPreferredSize(new java.awt.Dimension(940, 100));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_locTheoGia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_locTheoGia.setText("Lọc theo giá");
        jPanel11.add(lbl_locTheoGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, 30));

        lbl_locTheoSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_locTheoSP.setText("Lọc theo lọai sản phẩm");
        jPanel11.add(lbl_locTheoSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        lbl_locTheoNCC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_locTheoNCC.setText("Lọc theo nhà cung cấp");
        jPanel11.add(lbl_locTheoNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 200, 30));

        cbo_locTheoGia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbo_locTheoGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10000-1000000", "20000-5000000" }));
        jPanel11.add(cbo_locTheoGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 220, 40));

        cbo_loc_theoSP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbo_loc_theoSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SGK", "Truyện", "Tiểu thuyết", "Văn phòng phẩm", "Dụng cụ học tập" }));
        cbo_loc_theoSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_loc_theoSPActionPerformed(evt);
            }
        });
        jPanel11.add(cbo_loc_theoSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 270, 40));

        cbo_locTheoNCC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbo_locTheoNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NCC Gò Vấp", "NCC Tân Bình", "NCC Thủ Đức", "NCC Bình Thạnh" }));
        jPanel11.add(cbo_locTheoNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 250, 40));

        jPanel9.add(jPanel11, java.awt.BorderLayout.NORTH);

        jPanel12.setPreferredSize(new java.awt.Dimension(940, 200));
        jPanel12.setLayout(new java.awt.BorderLayout());

        tbl_sanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_sanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Loại SP", "Giá Nhập", "Giá Bán", "Tồn kho", "Nhà Cung Cấp", "Khuyến Mãi", "Bày bán"
            }
        ));
        tbl_sanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_sanPham);

        jPanel12.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void maSP_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maSP_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maSP_fieldActionPerformed

    private void cbo_NCC_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_NCC_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_NCC_fieldActionPerformed

    private void giaNhap_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giaNhap_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giaNhap_fieldActionPerformed

    private void tenSP_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenSP_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenSP_fieldActionPerformed

    private void btn_capNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capNhatActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_btn_capNhatActionPerformed

    private void cbo_loc_theoSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_loc_theoSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_loc_theoSPActionPerformed

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void tonKho_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tonKho_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tonKho_fieldActionPerformed

    private void maSP_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maSP_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maSP_txtActionPerformed

    private void btn_themMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_themMoiActionPerformed

    private void btn_xoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaTrangActionPerformed
        // TODO add your handling code here:
        maSP_field.setText("");
        tenSP_field.setText("");
        giaNhap_field.setText("");
        giaBan_field.setText("");
        tonKho_field.setText("");
        khuyenMai_field.setText("");
        bayban_field.setText("");
    }//GEN-LAST:event_btn_xoaTrangActionPerformed

    private void bayban_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayban_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayban_fieldActionPerformed

    private void giaBan_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giaBan_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giaBan_fieldActionPerformed

    private void tbl_sanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sanPhamMouseClicked
        // TODO add your handling code here:
        int r = tbl_sanPham.getSelectedRow();
        
        if(r >= 0){
            maSP_field.setText(tbl_sanPham.getValueAt(r, 0).toString());
            tenSP_field.setText(tbl_sanPham.getValueAt(r, 1).toString());
            giaNhap_field.setText(tbl_sanPham.getValueAt(r, 3).toString());
            giaBan_field.setText(tbl_sanPham.getValueAt(r, 4).toString());
            tonKho_field.setText(tbl_sanPham.getValueAt(r, 5).toString());
            khuyenMai_field.setText(tbl_sanPham.getValueAt(r, 7).toString());
            bayban_field.setText(tbl_sanPham.getValueAt(r, 8).toString());
            cbo_NCC_field.addItem(tbl_sanPham.getValueAt(r, 6).toString());
            cbo_loaiSP_field.addItem(tbl_sanPham.getValueAt(r, 2).toString());
        }else{
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hàng muốn thao tác!");
        }
    }//GEN-LAST:event_tbl_sanPhamMouseClicked

    private void btn_themMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themMoiMouseClicked
        // TODO add your handling code here:
        if(validData_SanPham()){
            SanPham sp = createSP();
            ArrayList<SanPham> dsSP = sp_dao.getDSSP();
            
            if(true){
                if(sp_dao.themSanPham(sp)){
                    XoaDuLieuTableSP();
                    DocLieuLenTableSanPham();
                    JOptionPane.showMessageDialog(this, "Thêm thành công!");
                }else{
                    JOptionPane.showMessageDialog(this, "Thêm thất bại! Có lỗi xảy ra");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Sản phẩm đã tồn tại! Vui lòng kiểm tra lại");
            }
        }
    }//GEN-LAST:event_btn_themMoiMouseClicked

    private void btn_timKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_timKiemMouseClicked
        // TODO add your handling code here:
        String maSP_searched = maSP_txt.getText().toString();
        
        if(!maSP_searched.trim().equals("")){
            XoaDuLieuTableSP();
            
            SanPham sp = sp_dao.getSP_TheoMa(maSP_searched);
            DefaultTableModel temp = (DefaultTableModel) tbl_sanPham.getModel();
            
            Object[] obj = {sp.getMaSP(), sp.getTenSP(), sp.getLoaiSP(), sp.getGiaNhapHang(), sp.getGiaBan(), sp.getSoLuongTonKho(), sp.getnCC().getMaNCC(), sp.getkM().getMaKM(), sp.getSoLuongBayBan()};
            temp.addRow(obj);
        }else{
            XoaDuLieuTableSP();
            DocLieuLenTableSanPham();
        }
            
    }//GEN-LAST:event_btn_timKiemMouseClicked

    private void btn_capNhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_capNhatMouseClicked
        // TODO add your handling code here:
        
        
        int r = tbl_sanPham.getSelectedRow();
        if(r < 0){
            JOptionPane.showMessageDialog(this, "Cần chọn sản phẩm cần cập nhật!");
        }
        
        if(validData_SanPham()){
            String maSP = maSP_field.getText();
            String tenSP = tenSP_field.getText();
            String cbo_loaiSP = String.valueOf(cbo_loaiSP_field.getSelectedItem());
            double giaNhap = Double.parseDouble(giaNhap_field.getText());
            double giaBan = Double.parseDouble(giaBan_field.getText());
            int tonKho = Integer.parseInt(tonKho_field.getText());
            String cbo_NCC = String.valueOf(cbo_NCC_field.getSelectedItem());
            String khuyenMai = khuyenMai_field.getText();
            int bayBan = Integer.parseInt(bayban_field.getText());

            SanPham sp = new SanPham(maSP, new KhuyenMai(khuyenMai), new NhaCungCap(cbo_NCC), tenSP, 
                                    cbo_loaiSP,giaNhap, giaBan, bayBan, tonKho, 0);
            
            if(sp_dao.updateSP(sp)){
                DefaultTableModel temp = (DefaultTableModel) tbl_sanPham.getModel();
                temp.removeRow(r);
                Object[] obj = {sp.getMaSP(), sp.getTenSP(), sp.getLoaiSP(), sp.getGiaNhapHang(), sp.getGiaBan(), sp.getSoLuongTonKho(), sp.getnCC().getMaNCC(), sp.getkM().getMaKM(), sp.getSoLuongBayBan()};
                temp.insertRow(r, obj);
                JOptionPane.showMessageDialog(this, "Cập nhật thành công sản phẩm có mã" + maSP);
            }else{
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại!!Có lỗi xảy ra!!");
            }
        }
    }//GEN-LAST:event_btn_capNhatMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayban_field;
    private javax.swing.JButton btn_capNhat;
    private javax.swing.JButton btn_themMoi;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_xoaTrang;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbo_NCC_field;
    private javax.swing.JComboBox<String> cbo_loaiSP_field;
    private javax.swing.JComboBox<String> cbo_locTheoGia;
    private javax.swing.JComboBox<String> cbo_locTheoNCC;
    private javax.swing.JComboBox<String> cbo_loc_theoSP;
    private javax.swing.JTextField giaBan_field;
    private javax.swing.JTextField giaNhap_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField khuyenMai_field;
    private javax.swing.JLabel lbl_Bayban;
    private javax.swing.JLabel lbl_NCC;
    private javax.swing.JLabel lbl_giaBan;
    private javax.swing.JLabel lbl_loai;
    private javax.swing.JLabel lbl_locTheoGia;
    private javax.swing.JLabel lbl_locTheoNCC;
    private javax.swing.JLabel lbl_locTheoSP;
    private javax.swing.JLabel lbl_masp;
    private javax.swing.JTextField maSP_field;
    private javax.swing.JTextField maSP_txt;
    private javax.swing.JPanel pnl_Center;
    private javax.swing.JPanel pnl_NCC;
    private javax.swing.JPanel pnl_TimKiem;
    private javax.swing.JPanel pnl_TonKho;
    private javax.swing.JPanel pnl_Top;
    private javax.swing.JPanel pnl_btn;
    private javax.swing.JPanel pnl_info;
    private javax.swing.JPanel pnl_info1;
    private javax.swing.JPanel pnl_info2;
    private javax.swing.JPanel pnl_info3;
    private javax.swing.JPanel pnl_maSP;
    private javax.swing.JPanel pnl_sanPham;
    private javax.swing.JTable tbl_sanPham;
    private javax.swing.JTextField tenSP_field;
    private javax.swing.JTextField tonKho_field;
    // End of variables declaration//GEN-END:variables
}
