/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import dao.KhachHang_DAO;
import entity.KhachHang;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MyPC
 */
public class Panel_customer extends javax.swing.JPanel {

    /**
     * Creates new form Panel_KhachHang
     */
    public Panel_customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_ThongTin = new javax.swing.JPanel();
        panel_ThongTin = new javax.swing.JPanel();
        thongTin1 = new javax.swing.JPanel();
        panel_maKH = new javax.swing.JPanel();
        label_maKH = new javax.swing.JLabel();
        text_maKH = new javax.swing.JTextField();
        panel_diaChi = new javax.swing.JPanel();
        label_diaChi = new javax.swing.JLabel();
        text_diaChi = new javax.swing.JTextField();
        panel_sĐT = new javax.swing.JPanel();
        label_sĐT = new javax.swing.JLabel();
        text_sĐT = new javax.swing.JTextField();
        panel_đTL = new javax.swing.JPanel();
        label_diemTichLuy = new javax.swing.JLabel();
        text_đTL = new javax.swing.JTextField();
        thongTin2 = new javax.swing.JPanel();
        panel_tenKH = new javax.swing.JPanel();
        label_tenKH = new javax.swing.JLabel();
        text_tenKH = new javax.swing.JTextField();
        panel_email = new javax.swing.JPanel();
        label_email = new javax.swing.JLabel();
        text_email = new javax.swing.JTextField();
        panel_tieuPhi = new javax.swing.JPanel();
        label_tieuPhi = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        thongTin3 = new javax.swing.JPanel();
        panel_gioiTinh = new javax.swing.JPanel();
        label_gioiTinh = new javax.swing.JLabel();
        cb_gioiTinh = new javax.swing.JComboBox<>();
        panel_ngaySinh = new javax.swing.JPanel();
        label_ngaySInh = new javax.swing.JLabel();
        cb_ngaySinh = new javax.swing.JComboBox<>();
        panel_rank = new javax.swing.JPanel();
        label_rank = new javax.swing.JLabel();
        cb_rank = new javax.swing.JComboBox<>();
        panel_bangThongTin = new javax.swing.JPanel();
        panel_btn = new javax.swing.JPanel();
        btn_timKiem = new javax.swing.JButton();
        text_timKiem = new javax.swing.JTextField();
        btn_themMoi = new javax.swing.JButton();
        btn_capNhat = new javax.swing.JButton();
        btn_xoaTrang = new javax.swing.JButton();
        bangtt = new javax.swing.JPanel();
        panel_loc = new javax.swing.JPanel();
        label_locTheoRank = new javax.swing.JLabel();
        cbb_locTheoRank = new javax.swing.JComboBox<>();
        label_locGioiTinh = new javax.swing.JLabel();
        cbb_locGioiTinh = new javax.swing.JComboBox<>();
        label_locTieuPhi = new javax.swing.JLabel();
        cbb_locTieuPhi = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_khachHang = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1200, 500));
        setLayout(new java.awt.BorderLayout());

        Panel_ThongTin.setLayout(new java.awt.BorderLayout());

        panel_ThongTin.setPreferredSize(new java.awt.Dimension(900, 350));
        panel_ThongTin.setLayout(new java.awt.GridLayout(1, 3));

        thongTin1.setPreferredSize(new java.awt.Dimension(300, 350));
        thongTin1.setLayout(new java.awt.GridLayout(4, 0));

        label_maKH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_maKH.setText("Mã KH:");

        text_maKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_maKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_maKHLayout = new javax.swing.GroupLayout(panel_maKH);
        panel_maKH.setLayout(panel_maKHLayout);
        panel_maKHLayout.setHorizontalGroup(
            panel_maKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_maKHLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label_maKH)
                .addGap(18, 18, 18)
                .addComponent(text_maKH, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_maKHLayout.setVerticalGroup(
            panel_maKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_maKHLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(panel_maKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_maKH)
                    .addComponent(text_maKH, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        thongTin1.add(panel_maKH);

        label_diaChi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_diaChi.setText("Địa chỉ:");

        javax.swing.GroupLayout panel_diaChiLayout = new javax.swing.GroupLayout(panel_diaChi);
        panel_diaChi.setLayout(panel_diaChiLayout);
        panel_diaChiLayout.setHorizontalGroup(
            panel_diaChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_diaChiLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(label_diaChi)
                .addGap(18, 18, 18)
                .addComponent(text_diaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_diaChiLayout.setVerticalGroup(
            panel_diaChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_diaChiLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel_diaChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_diaChi)
                    .addComponent(text_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        text_diaChi.getAccessibleContext().setAccessibleName("");

        thongTin1.add(panel_diaChi);

        label_sĐT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_sĐT.setText("SĐT:");

        javax.swing.GroupLayout panel_sĐTLayout = new javax.swing.GroupLayout(panel_sĐT);
        panel_sĐT.setLayout(panel_sĐTLayout);
        panel_sĐTLayout.setHorizontalGroup(
            panel_sĐTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_sĐTLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label_sĐT)
                .addGap(30, 30, 30)
                .addComponent(text_sĐT, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_sĐTLayout.setVerticalGroup(
            panel_sĐTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_sĐTLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panel_sĐTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_sĐT)
                    .addComponent(text_sĐT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        thongTin1.add(panel_sĐT);

        label_diemTichLuy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_diemTichLuy.setText("Điểm tích lũy:");

        javax.swing.GroupLayout panel_đTLLayout = new javax.swing.GroupLayout(panel_đTL);
        panel_đTL.setLayout(panel_đTLLayout);
        panel_đTLLayout.setHorizontalGroup(
            panel_đTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_đTLLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(label_diemTichLuy)
                .addGap(18, 18, 18)
                .addComponent(text_đTL, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_đTLLayout.setVerticalGroup(
            panel_đTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_đTLLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panel_đTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_diemTichLuy)
                    .addComponent(text_đTL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        thongTin1.add(panel_đTL);

        panel_ThongTin.add(thongTin1);

        thongTin2.setLayout(new java.awt.GridLayout(4, 0));

        label_tenKH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_tenKH.setText("Tên KH:");

        javax.swing.GroupLayout panel_tenKHLayout = new javax.swing.GroupLayout(panel_tenKH);
        panel_tenKH.setLayout(panel_tenKHLayout);
        panel_tenKHLayout.setHorizontalGroup(
            panel_tenKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tenKHLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(label_tenKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_tenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_tenKHLayout.setVerticalGroup(
            panel_tenKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tenKHLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panel_tenKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tenKH)
                    .addComponent(text_tenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        thongTin2.add(panel_tenKH);

        label_email.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_email.setText("Email:");

        text_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_emailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_emailLayout = new javax.swing.GroupLayout(panel_email);
        panel_email.setLayout(panel_emailLayout);
        panel_emailLayout.setHorizontalGroup(
            panel_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_emailLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label_email)
                .addGap(18, 18, 18)
                .addComponent(text_email, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_emailLayout.setVerticalGroup(
            panel_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_emailLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panel_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_email)
                    .addComponent(text_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        thongTin2.add(panel_email);

        label_tieuPhi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_tieuPhi.setText("Tiêu Phí:");

        javax.swing.GroupLayout panel_tieuPhiLayout = new javax.swing.GroupLayout(panel_tieuPhi);
        panel_tieuPhi.setLayout(panel_tieuPhiLayout);
        panel_tieuPhiLayout.setHorizontalGroup(
            panel_tieuPhiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tieuPhiLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(label_tieuPhi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_tieuPhiLayout.setVerticalGroup(
            panel_tieuPhiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tieuPhiLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panel_tieuPhiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tieuPhi)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        thongTin2.add(panel_tieuPhi);

        panel_ThongTin.add(thongTin2);

        thongTin3.setLayout(new java.awt.GridLayout(4, 0));

        label_gioiTinh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_gioiTinh.setText("Giới Tính:");

        cb_gioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        javax.swing.GroupLayout panel_gioiTinhLayout = new javax.swing.GroupLayout(panel_gioiTinh);
        panel_gioiTinh.setLayout(panel_gioiTinhLayout);
        panel_gioiTinhLayout.setHorizontalGroup(
            panel_gioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_gioiTinhLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label_gioiTinh)
                .addGap(18, 18, 18)
                .addComponent(cb_gioiTinh, 0, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_gioiTinhLayout.setVerticalGroup(
            panel_gioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_gioiTinhLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panel_gioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_gioiTinh))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        thongTin3.add(panel_gioiTinh);

        label_ngaySInh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_ngaySInh.setText("Ngày Sinh:");

        cb_ngaySinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", " " }));

        javax.swing.GroupLayout panel_ngaySinhLayout = new javax.swing.GroupLayout(panel_ngaySinh);
        panel_ngaySinh.setLayout(panel_ngaySinhLayout);
        panel_ngaySinhLayout.setHorizontalGroup(
            panel_ngaySinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ngaySinhLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(label_ngaySInh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_ngaySinh, 0, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_ngaySinhLayout.setVerticalGroup(
            panel_ngaySinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ngaySinhLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(panel_ngaySinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_ngaySInh)
                    .addComponent(cb_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        thongTin3.add(panel_ngaySinh);

        label_rank.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_rank.setText("Rank:");

        cb_rank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đồng", "Bạc", "Vàng", "Kim Cương", " " }));

        javax.swing.GroupLayout panel_rankLayout = new javax.swing.GroupLayout(panel_rank);
        panel_rank.setLayout(panel_rankLayout);
        panel_rankLayout.setHorizontalGroup(
            panel_rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rankLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label_rank)
                .addGap(51, 51, 51)
                .addComponent(cb_rank, 0, 205, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_rankLayout.setVerticalGroup(
            panel_rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rankLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panel_rankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_rank)
                    .addComponent(cb_rank, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        thongTin3.add(panel_rank);

        panel_ThongTin.add(thongTin3);

        Panel_ThongTin.add(panel_ThongTin, java.awt.BorderLayout.NORTH);

        panel_bangThongTin.setPreferredSize(new java.awt.Dimension(1000, 350));
        panel_bangThongTin.setLayout(new java.awt.BorderLayout());

        btn_timKiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_timKiem.setText("Tìm Kiếm");

        text_timKiem.setPreferredSize(new java.awt.Dimension(100, 22));

        btn_themMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_themMoi.setText("Thêm Mới");
        btn_themMoi.setBorder(null);
        btn_themMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themMoiActionPerformed(evt);
            }
        });

        btn_capNhat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_capNhat.setText("Cập Nhật");

        btn_xoaTrang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_xoaTrang.setText("Xóa Trắng");

        javax.swing.GroupLayout panel_btnLayout = new javax.swing.GroupLayout(panel_btn);
        panel_btn.setLayout(panel_btnLayout);
        panel_btnLayout.setHorizontalGroup(
            panel_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_timKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_btnLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btn_themMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(btn_xoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195)
                .addComponent(btn_capNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
            .addComponent(text_timKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_btnLayout.setVerticalGroup(
            panel_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_btnLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panel_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_themMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_capNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 29, Short.MAX_VALUE)
                .addComponent(btn_timKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_bangThongTin.add(panel_btn, java.awt.BorderLayout.PAGE_START);

        bangtt.setLayout(new java.awt.BorderLayout());

        label_locTheoRank.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_locTheoRank.setText("Lọc Theo Rank");

        cbb_locTheoRank.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbb_locTheoRank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đồng", "Bạc", "Vàng", "Kim Cương" }));

        label_locGioiTinh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_locGioiTinh.setText("Lọc Giới Tính");

        cbb_locGioiTinh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbb_locGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        label_locTieuPhi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_locTieuPhi.setText("Lọc Theo Tiêu Phí");

        cbb_locTieuPhi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbb_locTieuPhi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100000-10000000", "110000000-10000000" }));

        tbl_khachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã KH", "Tên KH", "Rank", "Tích lũy tiêu phí", "Giới Tính", "Email", "Ngày Sinh", "SĐT"
            }
        ));
        jScrollPane1.setViewportView(tbl_khachHang);

        javax.swing.GroupLayout panel_locLayout = new javax.swing.GroupLayout(panel_loc);
        panel_loc.setLayout(panel_locLayout);
        panel_locLayout.setHorizontalGroup(
            panel_locLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_locLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(panel_locLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panel_locLayout.createSequentialGroup()
                        .addComponent(label_locTheoRank)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_locGioiTinh)
                        .addGap(242, 242, 242)
                        .addComponent(label_locTieuPhi)
                        .addGap(17, 17, 17))
                    .addGroup(panel_locLayout.createSequentialGroup()
                        .addComponent(cbb_locTheoRank, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238)
                        .addComponent(cbb_locGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203)
                        .addComponent(cbb_locTieuPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        panel_locLayout.setVerticalGroup(
            panel_locLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_locLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_locLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_locTheoRank)
                    .addComponent(label_locGioiTinh)
                    .addComponent(label_locTieuPhi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_locLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbb_locTieuPhi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_locLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbb_locTheoRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbb_locGioiTinh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bangtt.add(panel_loc, java.awt.BorderLayout.CENTER);

        panel_bangThongTin.add(bangtt, java.awt.BorderLayout.CENTER);

        Panel_ThongTin.add(panel_bangThongTin, java.awt.BorderLayout.CENTER);

        add(Panel_ThongTin, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void text_maKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_maKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_maKHActionPerformed

    private void text_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_emailActionPerformed

    private void btn_themMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themMoiActionPerformed
        // TODO add your handling code here:
        String maKH = text_maKH.getText();
        String tenKH = text_tenKH.getText();
        String diaChi = text_diaChi.getText();
        String sĐT = text_sĐT.getText();  
        String email = text_email.getText();
        String đTL = text_đTL.getText();
        String cb_gioiTinh = String.valueOf(this.cb_gioiTinh.getSelectedItem());
        String cb_ngaySinh = String.valueOf(this.cb_ngaySinh.getSelectedItem());
        String cb_rank = String.valueOf(this.cb_rank.getSelectedItem());
        if(!maKH.isEmpty() && !tenKH.isEmpty() && !diaChi.isEmpty() && !sĐT.isEmpty() && !email.isEmpty()){
            Object obj[] = {maKH, tenKH, diaChi, sĐT, email, đTL, cb_gioiTinh, cb_ngaySinh,cb_rank};
            DefaultTableModel model_DSSP = (DefaultTableModel)tbl_khachHang.getModel();
            model_DSSP.addRow(obj);
        }else{
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
        }
    }//GEN-LAST:event_btn_themMoiActionPerformed
private void btn_xoaTrangActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        text_maKH.setText("");
        text_tenKH.setText("");
        text_diaChi.setText("");
        text_email.setText("");
        text_sĐT.setText("");
        text_đTL.setText("");
    } 
private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
       KhachHang_DAO khachHang_DAO = new KhachHang_DAO();
        String maKH_tim = text_timKiem.getText();
        KhachHang kh_tim = khachHang_DAO.getKH_TheoMa(maKH_tim);
        if(kh_tim != null){
            JOptionPane.showMessageDialog(this, "Đã tìm thấy sản phẩm!");
        }else{
            JOptionPane.showMessageDialog(this, "Sản phẩm không tồn tại!");
        }
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_ThongTin;
    private javax.swing.JPanel bangtt;
    private javax.swing.JButton btn_capNhat;
    private javax.swing.JButton btn_themMoi;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_xoaTrang;
    private javax.swing.JComboBox<String> cb_gioiTinh;
    private javax.swing.JComboBox<String> cb_ngaySinh;
    private javax.swing.JComboBox<String> cb_rank;
    private javax.swing.JComboBox<String> cbb_locGioiTinh;
    private javax.swing.JComboBox<String> cbb_locTheoRank;
    private javax.swing.JComboBox<String> cbb_locTieuPhi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label_diaChi;
    private javax.swing.JLabel label_diemTichLuy;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_gioiTinh;
    private javax.swing.JLabel label_locGioiTinh;
    private javax.swing.JLabel label_locTheoRank;
    private javax.swing.JLabel label_locTieuPhi;
    private javax.swing.JLabel label_maKH;
    private javax.swing.JLabel label_ngaySInh;
    private javax.swing.JLabel label_rank;
    private javax.swing.JLabel label_sĐT;
    private javax.swing.JLabel label_tenKH;
    private javax.swing.JLabel label_tieuPhi;
    private javax.swing.JPanel panel_ThongTin;
    private javax.swing.JPanel panel_bangThongTin;
    private javax.swing.JPanel panel_btn;
    private javax.swing.JPanel panel_diaChi;
    private javax.swing.JPanel panel_email;
    private javax.swing.JPanel panel_gioiTinh;
    private javax.swing.JPanel panel_loc;
    private javax.swing.JPanel panel_maKH;
    private javax.swing.JPanel panel_ngaySinh;
    private javax.swing.JPanel panel_rank;
    private javax.swing.JPanel panel_sĐT;
    private javax.swing.JPanel panel_tenKH;
    private javax.swing.JPanel panel_tieuPhi;
    private javax.swing.JPanel panel_đTL;
    private javax.swing.JTable tbl_khachHang;
    private javax.swing.JTextField text_diaChi;
    private javax.swing.JTextField text_email;
    private javax.swing.JTextField text_maKH;
    private javax.swing.JTextField text_sĐT;
    private javax.swing.JTextField text_tenKH;
    private javax.swing.JTextField text_timKiem;
    private javax.swing.JTextField text_đTL;
    private javax.swing.JPanel thongTin1;
    private javax.swing.JPanel thongTin2;
    private javax.swing.JPanel thongTin3;
    // End of variables declaration//GEN-END:variables
}
