/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Asus
 */
public class Panel_anylist extends javax.swing.JPanel {

    /**
     * Creates new form Panel_anylist
     */
    public Panel_anylist() {
        initComponents();
    }
    
    public void DoculieuLenTable() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnl_ThongKeDoanhThu = new javax.swing.JPanel();
        pnl_top = new javax.swing.JPanel();
        pnl_TKDT_info = new javax.swing.JPanel();
        pnl_LoaiThoiGian = new javax.swing.JPanel();
        lbl_LoaiThoiGian = new javax.swing.JLabel();
        cb_LoaiThoiGian = new javax.swing.JComboBox<>();
        pnl_NgayBatDau = new javax.swing.JPanel();
        lbl_NgayBatDau = new javax.swing.JLabel();
        date_NgayBatDau = new com.toedter.calendar.JDateChooser();
        pnl_NgayKetThuc = new javax.swing.JPanel();
        lbl_NgayKetThuc = new javax.swing.JLabel();
        date_NgayKetThuc = new com.toedter.calendar.JDateChooser();
        pnl_btn_TimKiem = new javax.swing.JPanel();
        btn_TimKiem = new javax.swing.JButton();
        pnl_center = new javax.swing.JPanel();
        pnl_SoLieu_TKDT = new javax.swing.JPanel();
        pnl_TongHD = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl_TongHD_title = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbl_TongHD = new javax.swing.JLabel();
        pnl_DoanhThu = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lbl_DoanhThu_title1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbl_DoanhThu = new javax.swing.JLabel();
        pnl_TongVon = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lbl_TongVon_title = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lbl_TongVon = new javax.swing.JLabel();
        pnl_LoiNhuan = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        lbl_LoiNhuan_title = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lbl_LoiNhuan = new javax.swing.JLabel();
        pnl_tabel_TKDT = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnl_ThongKeSanPham = new javax.swing.JPanel();
        pnl_top1 = new javax.swing.JPanel();
        pnl_TKDT_info1 = new javax.swing.JPanel();
        pnl_LoaiThoiGian1 = new javax.swing.JPanel();
        lbl_LoaiThoiGian1 = new javax.swing.JLabel();
        cb_LoaiThoiGian1 = new javax.swing.JComboBox<>();
        pnl_NgayBatDau1 = new javax.swing.JPanel();
        lbl_NgayBatDau1 = new javax.swing.JLabel();
        date_NgayBatDau1 = new com.toedter.calendar.JDateChooser();
        pnl_NgayKetThuc1 = new javax.swing.JPanel();
        lbl_NgayKetThuc1 = new javax.swing.JLabel();
        date_NgayKetThuc1 = new com.toedter.calendar.JDateChooser();
        pnl_btn_TimKiem1 = new javax.swing.JPanel();
        btn_TimKiem1 = new javax.swing.JButton();
        pnl_center1 = new javax.swing.JPanel();
        pnl_title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_tabel_TKDT1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnl_ThongKeDoanhThu.setLayout(new java.awt.BorderLayout());

        pnl_top.setBorder(javax.swing.BorderFactory.createTitledBorder("Bộ lọc"));
        pnl_top.setPreferredSize(new java.awt.Dimension(0, 170));
        pnl_top.setLayout(new java.awt.BorderLayout());

        pnl_TKDT_info.setPreferredSize(new java.awt.Dimension(0, 80));
        pnl_TKDT_info.setLayout(new java.awt.GridLayout(1, 3));

        lbl_LoaiThoiGian.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_LoaiThoiGian.setText("Loại Thời Gian:");
        pnl_LoaiThoiGian.add(lbl_LoaiThoiGian);

        cb_LoaiThoiGian.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cb_LoaiThoiGian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Báo cáo theo ngày", "Báo cáo theo tháng", "Báo cáo theo năm" }));
        cb_LoaiThoiGian.setPreferredSize(new java.awt.Dimension(220, 40));
        pnl_LoaiThoiGian.add(cb_LoaiThoiGian);

        pnl_TKDT_info.add(pnl_LoaiThoiGian);

        lbl_NgayBatDau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_NgayBatDau.setText("Ngày bắt đầu:");
        pnl_NgayBatDau.add(lbl_NgayBatDau);

        date_NgayBatDau.setPreferredSize(new java.awt.Dimension(220, 40));
        pnl_NgayBatDau.add(date_NgayBatDau);

        pnl_TKDT_info.add(pnl_NgayBatDau);

        lbl_NgayKetThuc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_NgayKetThuc.setText("Ngày kết thúc:");
        pnl_NgayKetThuc.add(lbl_NgayKetThuc);

        date_NgayKetThuc.setPreferredSize(new java.awt.Dimension(220, 40));
        pnl_NgayKetThuc.add(date_NgayKetThuc);

        pnl_TKDT_info.add(pnl_NgayKetThuc);

        pnl_top.add(pnl_TKDT_info, java.awt.BorderLayout.NORTH);

        pnl_btn_TimKiem.setPreferredSize(new java.awt.Dimension(1068, 70));

        btn_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_TimKiem.setText("Tìm kiếm");
        btn_TimKiem.setPreferredSize(new java.awt.Dimension(500, 50));
        pnl_btn_TimKiem.add(btn_TimKiem);

        pnl_top.add(pnl_btn_TimKiem, java.awt.BorderLayout.CENTER);

        pnl_ThongKeDoanhThu.add(pnl_top, java.awt.BorderLayout.NORTH);

        pnl_center.setLayout(new java.awt.BorderLayout());

        pnl_SoLieu_TKDT.setPreferredSize(new java.awt.Dimension(0, 150));
        pnl_SoLieu_TKDT.setLayout(new java.awt.GridLayout(1, 4));

        pnl_TongHD.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        pnl_TongHD.setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        lbl_TongHD_title.setBackground(new java.awt.Color(255, 255, 102));
        lbl_TongHD_title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_TongHD_title.setForeground(new java.awt.Color(0, 0, 0));
        lbl_TongHD_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TongHD_title.setText("Tổng số hóa đơn");
        jPanel1.add(lbl_TongHD_title);

        pnl_TongHD.add(jPanel1);

        jPanel5.setBackground(new java.awt.Color(255, 255, 102));

        lbl_TongHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_TongHD.setForeground(new java.awt.Color(0, 0, 0));
        lbl_TongHD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TongHD.setText("150");
        jPanel5.add(lbl_TongHD);

        pnl_TongHD.add(jPanel5);

        pnl_SoLieu_TKDT.add(pnl_TongHD);

        pnl_DoanhThu.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        pnl_DoanhThu.setLayout(new java.awt.GridLayout(2, 1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 102));

        lbl_DoanhThu_title1.setBackground(new java.awt.Color(255, 255, 102));
        lbl_DoanhThu_title1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_DoanhThu_title1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_DoanhThu_title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_DoanhThu_title1.setText("Doanh Thu");
        jPanel6.add(lbl_DoanhThu_title1);

        pnl_DoanhThu.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 102));

        lbl_DoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_DoanhThu.setForeground(new java.awt.Color(0, 0, 0));
        lbl_DoanhThu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_DoanhThu.setText(" 10.000.000");
        jPanel7.add(lbl_DoanhThu);

        pnl_DoanhThu.add(jPanel7);

        pnl_SoLieu_TKDT.add(pnl_DoanhThu);

        pnl_TongVon.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        pnl_TongVon.setLayout(new java.awt.GridLayout(2, 1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 102));

        lbl_TongVon_title.setBackground(new java.awt.Color(255, 255, 102));
        lbl_TongVon_title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_TongVon_title.setForeground(new java.awt.Color(0, 0, 0));
        lbl_TongVon_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TongVon_title.setText("Tổng vốn");
        jPanel8.add(lbl_TongVon_title);

        pnl_TongVon.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 102));

        lbl_TongVon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_TongVon.setForeground(new java.awt.Color(0, 0, 0));
        lbl_TongVon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TongVon.setText("4.000.000");
        jPanel9.add(lbl_TongVon);

        pnl_TongVon.add(jPanel9);

        pnl_SoLieu_TKDT.add(pnl_TongVon);

        pnl_LoiNhuan.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        pnl_LoiNhuan.setLayout(new java.awt.GridLayout(2, 1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 102));

        lbl_LoiNhuan_title.setBackground(new java.awt.Color(255, 255, 102));
        lbl_LoiNhuan_title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_LoiNhuan_title.setForeground(new java.awt.Color(0, 0, 0));
        lbl_LoiNhuan_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_LoiNhuan_title.setText("Lợi Nhuận");
        jPanel10.add(lbl_LoiNhuan_title);

        pnl_LoiNhuan.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 255, 102));

        lbl_LoiNhuan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_LoiNhuan.setForeground(new java.awt.Color(0, 0, 0));
        lbl_LoiNhuan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_LoiNhuan.setText("6.000.000");
        jPanel11.add(lbl_LoiNhuan);

        pnl_LoiNhuan.add(jPanel11);

        pnl_SoLieu_TKDT.add(pnl_LoiNhuan);

        pnl_center.add(pnl_SoLieu_TKDT, java.awt.BorderLayout.NORTH);

        pnl_tabel_TKDT.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HD", "Ngày Tạo", "Tiền vốn", "Doanh Thu", "Lợi Nhuận"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pnl_tabel_TKDT.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnl_center.add(pnl_tabel_TKDT, java.awt.BorderLayout.CENTER);

        pnl_ThongKeDoanhThu.add(pnl_center, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Thống kê doanh thu", pnl_ThongKeDoanhThu);

        pnl_ThongKeSanPham.setLayout(new java.awt.BorderLayout());

        pnl_top1.setBorder(javax.swing.BorderFactory.createTitledBorder("Bộ lọc"));
        pnl_top1.setPreferredSize(new java.awt.Dimension(0, 170));
        pnl_top1.setLayout(new java.awt.BorderLayout());

        pnl_TKDT_info1.setPreferredSize(new java.awt.Dimension(0, 70));
        pnl_TKDT_info1.setLayout(new java.awt.GridLayout(1, 3));

        lbl_LoaiThoiGian1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_LoaiThoiGian1.setText("Loại Thời Gian:");
        pnl_LoaiThoiGian1.add(lbl_LoaiThoiGian1);

        cb_LoaiThoiGian1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cb_LoaiThoiGian1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Báo cáo theo ngày", "Báo cáo theo tháng", "Báo cáo theo năm" }));
        cb_LoaiThoiGian1.setPreferredSize(new java.awt.Dimension(220, 40));
        pnl_LoaiThoiGian1.add(cb_LoaiThoiGian1);

        pnl_TKDT_info1.add(pnl_LoaiThoiGian1);

        lbl_NgayBatDau1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_NgayBatDau1.setText("Ngày bắt đầu:");
        pnl_NgayBatDau1.add(lbl_NgayBatDau1);

        date_NgayBatDau1.setPreferredSize(new java.awt.Dimension(220, 40));
        pnl_NgayBatDau1.add(date_NgayBatDau1);

        pnl_TKDT_info1.add(pnl_NgayBatDau1);

        lbl_NgayKetThuc1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_NgayKetThuc1.setText("Ngày kết thúc:");
        pnl_NgayKetThuc1.add(lbl_NgayKetThuc1);

        date_NgayKetThuc1.setPreferredSize(new java.awt.Dimension(220, 40));
        pnl_NgayKetThuc1.add(date_NgayKetThuc1);

        pnl_TKDT_info1.add(pnl_NgayKetThuc1);

        pnl_top1.add(pnl_TKDT_info1, java.awt.BorderLayout.NORTH);

        pnl_btn_TimKiem1.setPreferredSize(new java.awt.Dimension(1068, 80));

        btn_TimKiem1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_TimKiem1.setText("Tìm kiếm");
        btn_TimKiem1.setPreferredSize(new java.awt.Dimension(500, 50));
        pnl_btn_TimKiem1.add(btn_TimKiem1);

        pnl_top1.add(pnl_btn_TimKiem1, java.awt.BorderLayout.CENTER);

        pnl_ThongKeSanPham.add(pnl_top1, java.awt.BorderLayout.NORTH);

        pnl_center1.setLayout(new java.awt.BorderLayout());

        pnl_title.setPreferredSize(new java.awt.Dimension(1312, 50));
        pnl_title.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bảng thống kê sản phẩm bán chạy");
        pnl_title.add(jLabel1, java.awt.BorderLayout.CENTER);

        pnl_center1.add(pnl_title, java.awt.BorderLayout.PAGE_START);

        pnl_tabel_TKDT1.setLayout(new java.awt.BorderLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"SP001", "Sách tiếng viêt", "200", "20.000", "4.000.000", "2.000.000", " 2.000.000"},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên Sản Phẩm", "Đã bán", "Đơn giá", "Tổng doanh thu", "Tiền Vốn", "Lợi Nhuận"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        pnl_tabel_TKDT1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pnl_center1.add(pnl_tabel_TKDT1, java.awt.BorderLayout.CENTER);

        pnl_ThongKeSanPham.add(pnl_center1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Thống kê sản phẩm", pnl_ThongKeSanPham);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_TimKiem1;
    private javax.swing.JComboBox<String> cb_LoaiThoiGian;
    private javax.swing.JComboBox<String> cb_LoaiThoiGian1;
    private com.toedter.calendar.JDateChooser date_NgayBatDau;
    private com.toedter.calendar.JDateChooser date_NgayBatDau1;
    private com.toedter.calendar.JDateChooser date_NgayKetThuc;
    private com.toedter.calendar.JDateChooser date_NgayKetThuc1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_DoanhThu;
    private javax.swing.JLabel lbl_DoanhThu_title1;
    private javax.swing.JLabel lbl_LoaiThoiGian;
    private javax.swing.JLabel lbl_LoaiThoiGian1;
    private javax.swing.JLabel lbl_LoiNhuan;
    private javax.swing.JLabel lbl_LoiNhuan_title;
    private javax.swing.JLabel lbl_NgayBatDau;
    private javax.swing.JLabel lbl_NgayBatDau1;
    private javax.swing.JLabel lbl_NgayKetThuc;
    private javax.swing.JLabel lbl_NgayKetThuc1;
    private javax.swing.JLabel lbl_TongHD;
    private javax.swing.JLabel lbl_TongHD_title;
    private javax.swing.JLabel lbl_TongVon;
    private javax.swing.JLabel lbl_TongVon_title;
    private javax.swing.JPanel pnl_DoanhThu;
    private javax.swing.JPanel pnl_LoaiThoiGian;
    private javax.swing.JPanel pnl_LoaiThoiGian1;
    private javax.swing.JPanel pnl_LoiNhuan;
    private javax.swing.JPanel pnl_NgayBatDau;
    private javax.swing.JPanel pnl_NgayBatDau1;
    private javax.swing.JPanel pnl_NgayKetThuc;
    private javax.swing.JPanel pnl_NgayKetThuc1;
    private javax.swing.JPanel pnl_SoLieu_TKDT;
    private javax.swing.JPanel pnl_TKDT_info;
    private javax.swing.JPanel pnl_TKDT_info1;
    private javax.swing.JPanel pnl_ThongKeDoanhThu;
    private javax.swing.JPanel pnl_ThongKeSanPham;
    private javax.swing.JPanel pnl_TongHD;
    private javax.swing.JPanel pnl_TongVon;
    private javax.swing.JPanel pnl_btn_TimKiem;
    private javax.swing.JPanel pnl_btn_TimKiem1;
    private javax.swing.JPanel pnl_center;
    private javax.swing.JPanel pnl_center1;
    private javax.swing.JPanel pnl_tabel_TKDT;
    private javax.swing.JPanel pnl_tabel_TKDT1;
    private javax.swing.JPanel pnl_title;
    private javax.swing.JPanel pnl_top;
    private javax.swing.JPanel pnl_top1;
    // End of variables declaration//GEN-END:variables
}
