/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import dao.NhanVien_DAO;
import entity.NhanVien;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Panel_staff extends javax.swing.JPanel {
 private NhanVien_DAO nv_dao = new NhanVien_DAO();
    /**
     * Creates new form Panel_staff
     */
    public Panel_staff() {
        initComponents();
        DocDuLieuLenTableNhanVien();
    }

    public boolean validData_NV() {
        String maNV = txt_MaNV.getText().toString().trim();
        String tenNV = txt_TenNV.getText().toString().trim();
        String email = txt_Email.getText().toString().trim();
        String sDT = txt_SDT.getText().toString().trim();
        String diaChi = txt_DiaChi.getText().toString().trim();
        
        
       
        
        if(tenNV.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên NV không được rỗng!!!");
            return false;
        }
        
        if(email.isEmpty() || !email.matches("[a-zA-Z0-9]+@gmail.com")) {
            JOptionPane.showMessageDialog(this, "Email theo mẫu abc123@gmail.com");
            return false;
        }
        
        if(sDT.isEmpty() || !sDT.matches("0\\d{9}")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại phải có 10 số");
            return false;
        }
        
        if(diaChi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Địa chỉ không được rỗng!!!");
            return false;
        }
                
        
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnl_NhanVien = new javax.swing.JPanel();
        pnl_top = new javax.swing.JPanel();
        pnl_info_NV = new javax.swing.JPanel();
        pnl_info_1 = new javax.swing.JPanel();
        pnl_MaNV = new javax.swing.JPanel();
        lbl_MaNV = new javax.swing.JLabel();
        txt_MaNV = new javax.swing.JTextField();
        pnl_TenNV = new javax.swing.JPanel();
        lbl_TenNV = new javax.swing.JLabel();
        txt_TenNV = new javax.swing.JTextField();
        pnl_NS = new javax.swing.JPanel();
        lbl_NS = new javax.swing.JLabel();
        date_NS = new com.toedter.calendar.JDateChooser();
        pnl_info_2 = new javax.swing.JPanel();
        pnl_GioiTinh = new javax.swing.JPanel();
        lbl_GT = new javax.swing.JLabel();
        cb_GioiTinh = new javax.swing.JComboBox<>();
        pnl_SDT = new javax.swing.JPanel();
        lbl_SDT = new javax.swing.JLabel();
        txt_SDT = new javax.swing.JTextField();
        pnl_ChucVu = new javax.swing.JPanel();
        lbl_ChucVu = new javax.swing.JLabel();
        cb_ChucVu = new javax.swing.JComboBox<>();
        pnl_info_3 = new javax.swing.JPanel();
        pnl_Email = new javax.swing.JPanel();
        lbl_Email = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        pnl_DiaChi = new javax.swing.JPanel();
        lbl_DiaChi = new javax.swing.JLabel();
        txt_DiaChi = new javax.swing.JTextField();
        pnl_list_btn = new javax.swing.JPanel();
        btn_ThemMoi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_XoaTrang = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_CapNhat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_Xoa = new javax.swing.JButton();
        pnl_TimKiem = new javax.swing.JPanel();
        btn_TimKiem = new javax.swing.JButton();
        txt_TimKiem = new javax.swing.JTextField();
        pnl_center = new javax.swing.JPanel();
        pnl_BoLoc = new javax.swing.JPanel();
        pnl_LocTheoChucVu_wrap = new javax.swing.JPanel();
        pnl_LocTheoChucVu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbl_LocTheoCV = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cb_LocTheoCV = new javax.swing.JComboBox<>();
        pnl_LocTheoNamSinh_wrap = new javax.swing.JPanel();
        pnl_LocTheoNamSinh = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lbl_LocTheoNamSinh = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        date_LocTheoNS = new com.toedter.calendar.JYearChooser();
        pnl_LocTheoGT_wrap = new javax.swing.JPanel();
        pnl_LocTheoGT = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        bl_LocGT = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        cb_LocGT = new javax.swing.JComboBox<>();
        pnl_tabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_nhanVien = new javax.swing.JTable();
        pnl_TaiKhoan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        pnl_NhanVien.setLayout(new java.awt.BorderLayout());

        pnl_top.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"));
        pnl_top.setPreferredSize(new java.awt.Dimension(0, 320));
        pnl_top.setLayout(new java.awt.BorderLayout());

        pnl_info_NV.setPreferredSize(new java.awt.Dimension(0, 150));
        pnl_info_NV.setLayout(new java.awt.GridLayout(1, 4));

        pnl_info_1.setLayout(new java.awt.GridLayout(3, 1));

        lbl_MaNV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_MaNV.setText("Mã NV:");
        lbl_MaNV.setPreferredSize(new java.awt.Dimension(100, 25));
        pnl_MaNV.add(lbl_MaNV);

        txt_MaNV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_MaNV.setEnabled(false);
        txt_MaNV.setPreferredSize(new java.awt.Dimension(200, 35));
        pnl_MaNV.add(txt_MaNV);

        pnl_info_1.add(pnl_MaNV);

        lbl_TenNV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_TenNV.setText("Tên NV:");
        lbl_TenNV.setPreferredSize(new java.awt.Dimension(100, 25));
        pnl_TenNV.add(lbl_TenNV);

        txt_TenNV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_TenNV.setPreferredSize(new java.awt.Dimension(200, 35));
        pnl_TenNV.add(txt_TenNV);

        pnl_info_1.add(pnl_TenNV);

        lbl_NS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_NS.setText("Ngày Sinh:");
        lbl_NS.setPreferredSize(new java.awt.Dimension(100, 25));
        pnl_NS.add(lbl_NS);

        date_NS.setPreferredSize(new java.awt.Dimension(200, 35));
        pnl_NS.add(date_NS);

        pnl_info_1.add(pnl_NS);

        pnl_info_NV.add(pnl_info_1);

        pnl_info_2.setLayout(new java.awt.GridLayout(3, 1));

        lbl_GT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_GT.setText("Giới tính:");
        lbl_GT.setPreferredSize(new java.awt.Dimension(80, 25));
        pnl_GioiTinh.add(lbl_GT);

        cb_GioiTinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_GioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cb_GioiTinh.setPreferredSize(new java.awt.Dimension(230, 35));
        pnl_GioiTinh.add(cb_GioiTinh);

        pnl_info_2.add(pnl_GioiTinh);

        lbl_SDT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_SDT.setText("SĐT:");
        lbl_SDT.setPreferredSize(new java.awt.Dimension(80, 25));
        pnl_SDT.add(lbl_SDT);

        txt_SDT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_SDT.setPreferredSize(new java.awt.Dimension(230, 35));
        pnl_SDT.add(txt_SDT);

        pnl_info_2.add(pnl_SDT);

        lbl_ChucVu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_ChucVu.setText("Chức vụ: ");
        lbl_ChucVu.setPreferredSize(new java.awt.Dimension(80, 25));
        pnl_ChucVu.add(lbl_ChucVu);

        cb_ChucVu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_ChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên bán hàng", "Quản lý" }));
        cb_ChucVu.setPreferredSize(new java.awt.Dimension(230, 35));
        cb_ChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ChucVuActionPerformed(evt);
            }
        });
        pnl_ChucVu.add(cb_ChucVu);

        pnl_info_2.add(pnl_ChucVu);

        pnl_info_NV.add(pnl_info_2);

        pnl_info_3.setLayout(new java.awt.GridLayout(3, 1));

        lbl_Email.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Email.setText("Email:");
        lbl_Email.setPreferredSize(new java.awt.Dimension(80, 25));
        pnl_Email.add(lbl_Email);

        txt_Email.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_Email.setPreferredSize(new java.awt.Dimension(230, 35));
        pnl_Email.add(txt_Email);

        pnl_info_3.add(pnl_Email);

        lbl_DiaChi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_DiaChi.setText("Địa chỉ:");
        lbl_DiaChi.setPreferredSize(new java.awt.Dimension(80, 25));
        pnl_DiaChi.add(lbl_DiaChi);

        txt_DiaChi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_DiaChi.setPreferredSize(new java.awt.Dimension(230, 35));
        pnl_DiaChi.add(txt_DiaChi);

        pnl_info_3.add(pnl_DiaChi);

        pnl_info_NV.add(pnl_info_3);

        pnl_top.add(pnl_info_NV, java.awt.BorderLayout.NORTH);

        btn_ThemMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_ThemMoi.setText("Thêm Mới");
        btn_ThemMoi.setPreferredSize(new java.awt.Dimension(150, 40));
        btn_ThemMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThemMoiMouseClicked(evt);
            }
        });
        pnl_list_btn.add(btn_ThemMoi);

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pnl_list_btn.add(jPanel1);

        btn_XoaTrang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_XoaTrang.setText("Xóa Trắng");
        btn_XoaTrang.setPreferredSize(new java.awt.Dimension(150, 40));
        btn_XoaTrang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XoaTrangMouseClicked(evt);
            }
        });
        pnl_list_btn.add(btn_XoaTrang);

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pnl_list_btn.add(jPanel2);

        btn_CapNhat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_CapNhat.setText("Cập Nhật");
        btn_CapNhat.setPreferredSize(new java.awt.Dimension(150, 40));
        btn_CapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CapNhatMouseClicked(evt);
            }
        });
        pnl_list_btn.add(btn_CapNhat);

        jPanel3.setPreferredSize(new java.awt.Dimension(100, 40));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pnl_list_btn.add(jPanel3);

        btn_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Xoa.setText("Xóa");
        btn_Xoa.setPreferredSize(new java.awt.Dimension(150, 40));
        btn_Xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XoaMouseClicked(evt);
            }
        });
        pnl_list_btn.add(btn_Xoa);

        pnl_top.add(pnl_list_btn, java.awt.BorderLayout.CENTER);

        pnl_TimKiem.setPreferredSize(new java.awt.Dimension(1017, 60));
        pnl_TimKiem.setLayout(new java.awt.BorderLayout());

        btn_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TimKiem.setText("Tìm Kiếm");
        btn_TimKiem.setPreferredSize(new java.awt.Dimension(150, 36));
        pnl_TimKiem.add(btn_TimKiem, java.awt.BorderLayout.WEST);

        txt_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnl_TimKiem.add(txt_TimKiem, java.awt.BorderLayout.CENTER);

        pnl_top.add(pnl_TimKiem, java.awt.BorderLayout.SOUTH);

        pnl_NhanVien.add(pnl_top, java.awt.BorderLayout.NORTH);

        pnl_center.setLayout(new java.awt.BorderLayout());

        pnl_BoLoc.setPreferredSize(new java.awt.Dimension(0, 150));
        pnl_BoLoc.setLayout(new java.awt.GridLayout(1, 3));

        pnl_LocTheoChucVu_wrap.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 40, 10, 40));
        pnl_LocTheoChucVu_wrap.setLayout(new java.awt.BorderLayout());

        pnl_LocTheoChucVu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnl_LocTheoChucVu.setLayout(new java.awt.GridLayout(2, 1));

        lbl_LocTheoCV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_LocTheoCV.setText("Lọc theo chức vụ");
        jPanel4.add(lbl_LocTheoCV);

        pnl_LocTheoChucVu.add(jPanel4);

        cb_LocTheoCV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cb_LocTheoCV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản Lý", "Nhân Viên Bán Hàng" }));
        jPanel7.add(cb_LocTheoCV);

        pnl_LocTheoChucVu.add(jPanel7);

        pnl_LocTheoChucVu_wrap.add(pnl_LocTheoChucVu, java.awt.BorderLayout.CENTER);

        pnl_BoLoc.add(pnl_LocTheoChucVu_wrap);

        pnl_LocTheoNamSinh_wrap.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        pnl_LocTheoNamSinh_wrap.setLayout(new java.awt.BorderLayout());

        pnl_LocTheoNamSinh.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnl_LocTheoNamSinh.setLayout(new java.awt.GridLayout(2, 1));

        lbl_LocTheoNamSinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_LocTheoNamSinh.setText("Lọc theo năm sinh");
        jPanel8.add(lbl_LocTheoNamSinh);

        pnl_LocTheoNamSinh.add(jPanel8);

        date_LocTheoNS.setPreferredSize(new java.awt.Dimension(250, 35));
        jPanel9.add(date_LocTheoNS);

        pnl_LocTheoNamSinh.add(jPanel9);

        pnl_LocTheoNamSinh_wrap.add(pnl_LocTheoNamSinh, java.awt.BorderLayout.CENTER);

        pnl_BoLoc.add(pnl_LocTheoNamSinh_wrap);

        pnl_LocTheoGT_wrap.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        pnl_LocTheoGT_wrap.setLayout(new java.awt.BorderLayout());

        pnl_LocTheoGT.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnl_LocTheoGT.setLayout(new java.awt.GridLayout(2, 1));

        bl_LocGT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bl_LocGT.setText("Lọc theo giới tính");
        jPanel10.add(bl_LocGT);

        pnl_LocTheoGT.add(jPanel10);

        cb_LocGT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cb_LocGT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cb_LocGT.setPreferredSize(new java.awt.Dimension(250, 35));
        jPanel11.add(cb_LocGT);

        pnl_LocTheoGT.add(jPanel11);

        pnl_LocTheoGT_wrap.add(pnl_LocTheoGT, java.awt.BorderLayout.CENTER);

        pnl_BoLoc.add(pnl_LocTheoGT_wrap);

        pnl_center.add(pnl_BoLoc, java.awt.BorderLayout.NORTH);

        pnl_tabel.setLayout(new java.awt.BorderLayout());

        tbl_nhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Tên NV", "Chức Vụ", "Giới Tính", "Địa Chỉ", "Email", "Ngày Sinh", "SĐT"
            }
        ));
        jScrollPane1.setViewportView(tbl_nhanVien);

        pnl_tabel.add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        pnl_center.add(pnl_tabel, java.awt.BorderLayout.CENTER);

        pnl_NhanVien.add(pnl_center, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Nhân viên", pnl_NhanVien);

        jLabel2.setText("ádalskjdlaskjlkdjasldjlasd");

        javax.swing.GroupLayout pnl_TaiKhoanLayout = new javax.swing.GroupLayout(pnl_TaiKhoan);
        pnl_TaiKhoan.setLayout(pnl_TaiKhoanLayout);
        pnl_TaiKhoanLayout.setHorizontalGroup(
            pnl_TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TaiKhoanLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel2)
                .addContainerGap(1157, Short.MAX_VALUE))
        );
        pnl_TaiKhoanLayout.setVerticalGroup(
            pnl_TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_TaiKhoanLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel2)
                .addContainerGap(585, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản Lý Tài Khoản", pnl_TaiKhoan);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
        
    
    public void DocDuLieuLenTableNhanVien(){
        ArrayList<NhanVien> dsNV = nv_dao.getAllNV();
        DefaultTableModel temp = (DefaultTableModel) tbl_nhanVien.getModel();
        
        for(NhanVien nv : dsNV){
            Object[] obj = {nv.getMaNV(),nv.getTenNV(), nv.getChucVu(), nv.getGioiTinh(),nv.getDiaChi(),nv.getEmail(), nv.getNgaySinh(),nv.getsDT()};
            temp.addRow(obj);
        }         
    }
     public void XoaDuLieuTableNV(){
        DefaultTableModel temp = (DefaultTableModel) tbl_nhanVien.getModel();
        temp.getDataVector().removeAllElements();
    }
    private void cb_ChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_ChucVuActionPerformed

    private void btn_ThemMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThemMoiMouseClicked
        // TODO add your handling code here:
        if(validData_NV()) {
            NhanVien nv = createNV();
            ArrayList<NhanVien> dsNCC = nv_dao.getAllNV();

            if(true) {
                if(nv_dao.ThemNV(nv)) {
                    XoaDuLieuTableNV();
                    DocDuLieuLenTableNhanVien();
                    JOptionPane.showMessageDialog(this, "Thêm thành công!!!");
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bai!!! Có lỗi xảy ra!!!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nhân viên đã tồn tai!!!");
            }
        }
    }//GEN-LAST:event_btn_ThemMoiMouseClicked

    private void btn_XoaTrangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XoaTrangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_XoaTrangMouseClicked

    private void btn_CapNhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CapNhatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CapNhatMouseClicked

    private void btn_XoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XoaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_XoaMouseClicked
public NhanVien createNV() {
        String maNV = txt_MaNV.getText().toString();
        String tenNV = txt_TenNV.getText().toString();
        String chucVu= cb_ChucVu.getName().toString();
        String gioiTinh = cb_GioiTinh.getName().toString();
        String diaChi = txt_DiaChi.getText().toString();
        String email = txt_Email.getText().toString();
        Date ngaySinh = date_NS.getDate();
        String sDT = txt_SDT.getText().toString();
        NhanVien nv = new NhanVien(maNV, tenNV, chucVu, gioiTinh, diaChi, email, ngaySinh, sDT);
        
         return nv;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bl_LocGT;
    private javax.swing.JButton btn_CapNhat;
    private javax.swing.JButton btn_ThemMoi;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_XoaTrang;
    private javax.swing.JComboBox<String> cb_ChucVu;
    private javax.swing.JComboBox<String> cb_GioiTinh;
    private javax.swing.JComboBox<String> cb_LocGT;
    private javax.swing.JComboBox<String> cb_LocTheoCV;
    private com.toedter.calendar.JYearChooser date_LocTheoNS;
    private com.toedter.calendar.JDateChooser date_NS;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_ChucVu;
    private javax.swing.JLabel lbl_DiaChi;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_GT;
    private javax.swing.JLabel lbl_LocTheoCV;
    private javax.swing.JLabel lbl_LocTheoNamSinh;
    private javax.swing.JLabel lbl_MaNV;
    private javax.swing.JLabel lbl_NS;
    private javax.swing.JLabel lbl_SDT;
    private javax.swing.JLabel lbl_TenNV;
    private javax.swing.JPanel pnl_BoLoc;
    private javax.swing.JPanel pnl_ChucVu;
    private javax.swing.JPanel pnl_DiaChi;
    private javax.swing.JPanel pnl_Email;
    private javax.swing.JPanel pnl_GioiTinh;
    private javax.swing.JPanel pnl_LocTheoChucVu;
    private javax.swing.JPanel pnl_LocTheoChucVu_wrap;
    private javax.swing.JPanel pnl_LocTheoGT;
    private javax.swing.JPanel pnl_LocTheoGT_wrap;
    private javax.swing.JPanel pnl_LocTheoNamSinh;
    private javax.swing.JPanel pnl_LocTheoNamSinh_wrap;
    private javax.swing.JPanel pnl_MaNV;
    private javax.swing.JPanel pnl_NS;
    private javax.swing.JPanel pnl_NhanVien;
    private javax.swing.JPanel pnl_SDT;
    private javax.swing.JPanel pnl_TaiKhoan;
    private javax.swing.JPanel pnl_TenNV;
    private javax.swing.JPanel pnl_TimKiem;
    private javax.swing.JPanel pnl_center;
    private javax.swing.JPanel pnl_info_1;
    private javax.swing.JPanel pnl_info_2;
    private javax.swing.JPanel pnl_info_3;
    private javax.swing.JPanel pnl_info_NV;
    private javax.swing.JPanel pnl_list_btn;
    private javax.swing.JPanel pnl_tabel;
    private javax.swing.JPanel pnl_top;
    private javax.swing.JTable tbl_nhanVien;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenNV;
    private javax.swing.JTextField txt_TimKiem;
    // End of variables declaration//GEN-END:variables
}
