/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlysach;

/**
 *
 * @author Asus
 */
public class Panel_bill extends javax.swing.JPanel {

    /**
     * Creates new form Panel_bill
     */
    public Panel_bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnl_HoaDon = new javax.swing.JPanel();
        pnl_top = new javax.swing.JPanel();
        pnl_HD_info = new javax.swing.JPanel();
        pnl_MaHD = new javax.swing.JPanel();
        lbl_MaHD = new javax.swing.JLabel();
        txt_MaHD = new javax.swing.JTextField();
        pnl_NgayTao = new javax.swing.JPanel();
        lbl_NgayTao = new javax.swing.JLabel();
        date_NgayTao = new com.toedter.calendar.JDateChooser();
        pnl_NhanVien = new javax.swing.JPanel();
        lbl_NhanVien = new javax.swing.JLabel();
        txt_NhanVien = new javax.swing.JTextField();
        pnl_KhachHang = new javax.swing.JPanel();
        lbl_KhachHang = new javax.swing.JLabel();
        txt_KhachHang = new javax.swing.JTextField();
        pnl_HD_TimKiem = new javax.swing.JPanel();
        btn_TimKiem = new javax.swing.JButton();
        txt_TimKiem = new javax.swing.JTextField();
        pnl_center = new javax.swing.JPanel();
        pnl_BoLoc = new javax.swing.JPanel();
        pnl_LocTheoNgay = new javax.swing.JPanel();
        pnl_LocTheoNgay_wrap = new javax.swing.JPanel();
        pnl_LocTheoNgay_title = new javax.swing.JPanel();
        lbl_LocTheoNgay_title = new javax.swing.JLabel();
        pnl_Date_LocTheoNgay = new javax.swing.JPanel();
        date_LocTheoNgay = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pnl_Tabel = new javax.swing.JPanel();
        pnl_DoiTra = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(1280, 362));
        setPreferredSize(new java.awt.Dimension(476, 450));
        setLayout(new java.awt.BorderLayout());

        pnl_HoaDon.setLayout(new java.awt.BorderLayout());

        pnl_top.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Hóa Đơn"));
        pnl_top.setPreferredSize(new java.awt.Dimension(10, 200));
        pnl_top.setLayout(new java.awt.BorderLayout());

        pnl_HD_info.setPreferredSize(new java.awt.Dimension(10, 130));
        pnl_HD_info.setLayout(new java.awt.GridLayout(2, 2));

        lbl_MaHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_MaHD.setText("MÃ HD:");
        lbl_MaHD.setPreferredSize(new java.awt.Dimension(120, 25));
        pnl_MaHD.add(lbl_MaHD);

        txt_MaHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_MaHD.setPreferredSize(new java.awt.Dimension(350, 40));
        pnl_MaHD.add(txt_MaHD);

        pnl_HD_info.add(pnl_MaHD);

        lbl_NgayTao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_NgayTao.setText("Ngày Tạo:");
        lbl_NgayTao.setPreferredSize(new java.awt.Dimension(120, 25));
        pnl_NgayTao.add(lbl_NgayTao);

        date_NgayTao.setPreferredSize(new java.awt.Dimension(350, 40));
        pnl_NgayTao.add(date_NgayTao);

        pnl_HD_info.add(pnl_NgayTao);

        lbl_NhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_NhanVien.setText("Nhân Viên: ");
        lbl_NhanVien.setPreferredSize(new java.awt.Dimension(120, 25));
        pnl_NhanVien.add(lbl_NhanVien);

        txt_NhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_NhanVien.setPreferredSize(new java.awt.Dimension(350, 40));
        pnl_NhanVien.add(txt_NhanVien);

        pnl_HD_info.add(pnl_NhanVien);

        lbl_KhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_KhachHang.setText("Khách Hàng:");
        lbl_KhachHang.setPreferredSize(new java.awt.Dimension(120, 25));
        pnl_KhachHang.add(lbl_KhachHang);

        txt_KhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_KhachHang.setPreferredSize(new java.awt.Dimension(350, 40));
        pnl_KhachHang.add(txt_KhachHang);

        pnl_HD_info.add(pnl_KhachHang);

        pnl_top.add(pnl_HD_info, java.awt.BorderLayout.NORTH);

        pnl_HD_TimKiem.setPreferredSize(new java.awt.Dimension(10, 70));
        pnl_HD_TimKiem.setLayout(new java.awt.BorderLayout());

        btn_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_TimKiem.setText("Tìm kiếm");
        pnl_HD_TimKiem.add(btn_TimKiem, java.awt.BorderLayout.WEST);

        txt_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnl_HD_TimKiem.add(txt_TimKiem, java.awt.BorderLayout.CENTER);

        pnl_top.add(pnl_HD_TimKiem, java.awt.BorderLayout.CENTER);

        pnl_HoaDon.add(pnl_top, java.awt.BorderLayout.NORTH);

        pnl_center.setLayout(new java.awt.BorderLayout());

        pnl_BoLoc.setPreferredSize(new java.awt.Dimension(10, 150));
        pnl_BoLoc.setLayout(new java.awt.GridLayout(1, 3));

        pnl_LocTheoNgay.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        pnl_LocTheoNgay.setLayout(new java.awt.BorderLayout());

        pnl_LocTheoNgay_wrap.setBorder(javax.swing.BorderFactory.createTitledBorder("Lọc theo ngày"));
        pnl_LocTheoNgay_wrap.setLayout(new java.awt.GridLayout(2, 1));

        pnl_LocTheoNgay_title.setLayout(new java.awt.BorderLayout());

        lbl_LocTheoNgay_title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_LocTheoNgay_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_LocTheoNgay_title.setText("Lọc theo ngày");
        pnl_LocTheoNgay_title.add(lbl_LocTheoNgay_title, java.awt.BorderLayout.CENTER);

        pnl_LocTheoNgay_wrap.add(pnl_LocTheoNgay_title);

        pnl_Date_LocTheoNgay.setLayout(new java.awt.BorderLayout());
        pnl_Date_LocTheoNgay.add(date_LocTheoNgay, java.awt.BorderLayout.CENTER);

        pnl_LocTheoNgay_wrap.add(pnl_Date_LocTheoNgay);

        pnl_LocTheoNgay.add(pnl_LocTheoNgay_wrap, java.awt.BorderLayout.CENTER);

        pnl_BoLoc.add(pnl_LocTheoNgay);
        pnl_BoLoc.add(jPanel2);
        pnl_BoLoc.add(jPanel3);

        pnl_center.add(pnl_BoLoc, java.awt.BorderLayout.NORTH);
        pnl_center.add(pnl_Tabel, java.awt.BorderLayout.CENTER);

        pnl_HoaDon.add(pnl_center, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Hóa đơn", pnl_HoaDon);
        jTabbedPane1.addTab("Hóa đơn đổi trả", pnl_DoiTra);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_TimKiem;
    private com.toedter.calendar.JDateChooser date_LocTheoNgay;
    private com.toedter.calendar.JDateChooser date_NgayTao;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_KhachHang;
    private javax.swing.JLabel lbl_LocTheoNgay_title;
    private javax.swing.JLabel lbl_MaHD;
    private javax.swing.JLabel lbl_NgayTao;
    private javax.swing.JLabel lbl_NhanVien;
    private javax.swing.JPanel pnl_BoLoc;
    private javax.swing.JPanel pnl_Date_LocTheoNgay;
    private javax.swing.JPanel pnl_DoiTra;
    private javax.swing.JPanel pnl_HD_TimKiem;
    private javax.swing.JPanel pnl_HD_info;
    private javax.swing.JPanel pnl_HoaDon;
    private javax.swing.JPanel pnl_KhachHang;
    private javax.swing.JPanel pnl_LocTheoNgay;
    private javax.swing.JPanel pnl_LocTheoNgay_title;
    private javax.swing.JPanel pnl_LocTheoNgay_wrap;
    private javax.swing.JPanel pnl_MaHD;
    private javax.swing.JPanel pnl_NgayTao;
    private javax.swing.JPanel pnl_NhanVien;
    private javax.swing.JPanel pnl_Tabel;
    private javax.swing.JPanel pnl_center;
    private javax.swing.JPanel pnl_top;
    private javax.swing.JTextField txt_KhachHang;
    private javax.swing.JTextField txt_MaHD;
    private javax.swing.JTextField txt_NhanVien;
    private javax.swing.JTextField txt_TimKiem;
    // End of variables declaration//GEN-END:variables
}
