/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlysach;

/**
 *
 * @author Asus
 */
public class Panel_cart extends javax.swing.JPanel {
    /**
     * Creates new form Panel_product
     */
    public Panel_cart() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_product = new javax.swing.JPanel();
        scroll_table = new javax.swing.JScrollPane();
        tabel_product = new javax.swing.JTable();
        pnl_bill = new javax.swing.JPanel();
        scroll_bill = new javax.swing.JScrollPane();
        tabel_bill = new javax.swing.JTable();
        pnl_thanhToan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pnl_search_product = new javax.swing.JPanel();
        txt_search_MáP = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnl_product.setLayout(new java.awt.BorderLayout());

        tabel_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"SP001", "Sách tiếng việt", "Sách", "25000", "0", "125", "500", "NCC001"}
            },
            new String [] {
                "Mã SP", "Tên", "Loại", "Đơn giá", "Thuế VAT", "số lượng bày bán", "tồn kho", "được nhập từ"
            }
        ));
        scroll_table.setViewportView(tabel_product);

        pnl_product.add(scroll_table, java.awt.BorderLayout.CENTER);

        add(pnl_product, java.awt.BorderLayout.CENTER);

        pnl_bill.setPreferredSize(new java.awt.Dimension(550, 100));
        pnl_bill.setLayout(new java.awt.BorderLayout());

        tabel_bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Sách tiếng việt", "25000", "5", "125000"}
            },
            new String [] {
                "Tên SP", "Đơn giá(Có VAT)", "Số lượng", " Thành tiền"
            }
        ));
        scroll_bill.setViewportView(tabel_bill);

        pnl_bill.add(scroll_bill, java.awt.BorderLayout.CENTER);

        pnl_thanhToan.setPreferredSize(new java.awt.Dimension(100, 400));
        pnl_thanhToan.setLayout(new javax.swing.BoxLayout(pnl_thanhToan, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tổng tiền: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 400, 40));

        pnl_thanhToan.add(jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Số điện thoại:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Số điện thoại:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 400, 40));

        pnl_thanhToan.add(jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(490, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 140, 40));
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 230, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Khách hàng:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        pnl_thanhToan.add(jPanel3);

        jPanel4.setPreferredSize(new java.awt.Dimension(490, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền mặt", "Chuyển khoản", "Quét QR" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 400, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Thanh Toán:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        pnl_thanhToan.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(490, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Tiền nhận: ");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel5.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 400, 40));

        pnl_thanhToan.add(jPanel5);

        jPanel6.setMinimumSize(new java.awt.Dimension(490, 0));
        jPanel6.setPreferredSize(new java.awt.Dimension(490, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tiền thừa:");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel6.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 400, 40));

        pnl_thanhToan.add(jPanel6);

        jPanel7.setPreferredSize(new java.awt.Dimension(130, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Tạo thẻ ");
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 120, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Thanh toán");
        jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 40));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Xuất hóa đơn");
        jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 160, 40));

        pnl_thanhToan.add(jPanel7);

        pnl_bill.add(pnl_thanhToan, java.awt.BorderLayout.PAGE_END);

        add(pnl_bill, java.awt.BorderLayout.LINE_END);

        pnl_search_product.setPreferredSize(new java.awt.Dimension(10, 50));
        pnl_search_product.setLayout(new java.awt.BorderLayout());

        txt_search_MáP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnl_search_product.add(txt_search_MáP, java.awt.BorderLayout.CENTER);

        btn_search.setText("TÌm kiếm");
        btn_search.setPreferredSize(new java.awt.Dimension(150, 27));
        pnl_search_product.add(btn_search, java.awt.BorderLayout.EAST);

        add(pnl_search_product, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_search;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel pnl_bill;
    private javax.swing.JPanel pnl_product;
    private javax.swing.JPanel pnl_search_product;
    private javax.swing.JPanel pnl_thanhToan;
    private javax.swing.JScrollPane scroll_bill;
    private javax.swing.JScrollPane scroll_table;
    private javax.swing.JTable tabel_bill;
    private javax.swing.JTable tabel_product;
    private javax.swing.JTextField txt_search_MáP;
    // End of variables declaration//GEN-END:variables
}
